#!/usr/bin/env python3
"""
Frame Encoder for PhantomFPGA ASCII Animation Streaming

Reads ASCII frame files and generates:
1. frames.bin - Binary blob with all frames (for verification)
2. frames_data.h - C header with embedded frame data (for QEMU)

Frame format (5120 bytes each):
  Offset  Size   Field
  ------  ----   -----
  0x0000  4      magic (0xF00DFACE)
  0x0004  4      sequence (0-249)
  0x0008  8      reserved (must be 0)
  0x0010  4995   ASCII frame data (45 rows x 110 cols + newlines)
  0x1393  105    zero padding
  0x13FC  4      CRC32 (of bytes 0x0000-0x13FB)
  ------  ----
          5120   TOTAL

Usage:
    ./encode_frames.py assets/frames/ platform/qemu/src/hw/misc/
"""

import os
import sys
import struct
from pathlib import Path


# Frame format constants
FRAME_MAGIC = 0xF00DFACE
FRAME_SIZE = 5120
HEADER_SIZE = 16          # magic(4) + sequence(4) + reserved(8)
FRAME_DATA_SIZE = 4995    # 45 rows x 110 cols + 44 newlines
PADDING_SIZE = 105        # To align to 5120 total (5116 before CRC)
CRC_SIZE = 4
FRAME_COUNT = 250

# CRC32 table (IEEE 802.3 polynomial)
CRC32_TABLE = None

def init_crc32_table():
    """Initialize CRC32 lookup table."""
    global CRC32_TABLE
    CRC32_TABLE = []
    for i in range(256):
        crc = i
        for _ in range(8):
            if crc & 1:
                crc = (crc >> 1) ^ 0xEDB88320
            else:
                crc >>= 1
        CRC32_TABLE.append(crc)

def compute_crc32(data):
    """Compute CRC32 of data bytes."""
    crc = 0xFFFFFFFF
    for byte in data:
        crc = CRC32_TABLE[(crc ^ byte) & 0xFF] ^ (crc >> 8)
    return crc ^ 0xFFFFFFFF

def read_frame_file(filepath):
    """Read a single frame file and return its content as bytes."""
    with open(filepath, 'rb') as f:
        data = f.read()

    if len(data) != FRAME_DATA_SIZE:
        print(f"Warning: {filepath} is {len(data)} bytes, expected {FRAME_DATA_SIZE}")
        # Pad or truncate to exact size
        if len(data) < FRAME_DATA_SIZE:
            data = data + b'\n' * (FRAME_DATA_SIZE - len(data))
        else:
            data = data[:FRAME_DATA_SIZE]

    return data

def build_frame(sequence, frame_data):
    """Build a complete 5120-byte frame with header and CRC."""
    # Header: magic(4) + sequence(4) + reserved(8)
    header = struct.pack('<IIQ', FRAME_MAGIC, sequence, 0)
    assert len(header) == HEADER_SIZE

    # Ensure frame data is exactly FRAME_DATA_SIZE bytes
    assert len(frame_data) == FRAME_DATA_SIZE

    # Padding
    padding = b'\x00' * PADDING_SIZE

    # Combine header + data + padding (everything before CRC)
    pre_crc = header + frame_data + padding
    assert len(pre_crc) == FRAME_SIZE - CRC_SIZE  # 5116 bytes

    # Compute CRC32 of everything before CRC field
    crc = compute_crc32(pre_crc)
    crc_bytes = struct.pack('<I', crc)

    # Complete frame
    frame = pre_crc + crc_bytes
    assert len(frame) == FRAME_SIZE

    return frame

def generate_c_header(frames_data, output_path):
    """Generate C header file with embedded frame data."""

    with open(output_path, 'w') as f:
        f.write("""\
/*
 * PhantomFPGA Pre-built ASCII Animation Frames
 *
 * This file is auto-generated by tools/encode_frames.py
 * Do not edit manually!
 *
 * Contains 250 pre-built frames (10 seconds at 25 fps, loops)
 * Each frame is exactly 5120 bytes with header and CRC.
 *
 * Frame format:
 *   0x0000: magic (0xF00DFACE)
 *   0x0004: sequence (0-249)
 *   0x0008: reserved (must be 0)
 *   0x0010: ASCII frame data (4995 bytes)
 *   0x1393: zero padding (105 bytes)
 *   0x13FC: CRC32 (of bytes 0x0000-0x13FB)
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef PHANTOMFPGA_FRAMES_DATA_H
#define PHANTOMFPGA_FRAMES_DATA_H

#define PHANTOMFPGA_FRAME_SIZE      5120
#define PHANTOMFPGA_FRAME_COUNT     250
#define PHANTOMFPGA_FRAME_DATA_SIZE 4995
#define PHANTOMFPGA_FRAME_ROWS      45
#define PHANTOMFPGA_FRAME_COLS      110

/* All 250 frames concatenated (1,280,000 bytes total) */
static const uint8_t phantomfpga_frames[PHANTOMFPGA_FRAME_COUNT * PHANTOMFPGA_FRAME_SIZE] = {
""")

        total_bytes = len(frames_data)
        bytes_per_line = 16

        for i in range(0, total_bytes, bytes_per_line):
            chunk = frames_data[i:i+bytes_per_line]
            hex_str = ', '.join(f'0x{b:02x}' for b in chunk)

            # Add comment every frame boundary
            if i % FRAME_SIZE == 0:
                frame_num = i // FRAME_SIZE
                f.write(f'\n    /* Frame {frame_num} */\n')

            if i + bytes_per_line >= total_bytes:
                f.write(f'    {hex_str}\n')
            else:
                f.write(f'    {hex_str},\n')

        f.write("""\
};

#endif /* PHANTOMFPGA_FRAMES_DATA_H */
""")

def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <frames_dir> <output_dir>")
        print(f"  frames_dir: Directory containing frame_0001.txt - frame_0250.txt")
        print(f"  output_dir: Directory to write frames_data.h")
        sys.exit(1)

    frames_dir = Path(sys.argv[1])
    output_dir = Path(sys.argv[2])

    if not frames_dir.is_dir():
        print(f"Error: {frames_dir} is not a directory")
        sys.exit(1)

    if not output_dir.is_dir():
        print(f"Error: {output_dir} is not a directory")
        sys.exit(1)

    # Initialize CRC table
    init_crc32_table()

    print(f"Reading frames from {frames_dir}")
    print(f"Output directory: {output_dir}")

    # Build all frames
    all_frames = b''

    for seq in range(FRAME_COUNT):
        frame_num = seq + 1  # Files are 1-indexed
        frame_file = frames_dir / f"frame_{frame_num:04d}.txt"

        if not frame_file.exists():
            print(f"Error: Missing frame file: {frame_file}")
            sys.exit(1)

        frame_data = read_frame_file(frame_file)
        frame = build_frame(seq, frame_data)
        all_frames += frame

        if (seq + 1) % 50 == 0:
            print(f"  Processed {seq + 1}/{FRAME_COUNT} frames")

    expected_size = FRAME_COUNT * FRAME_SIZE
    if len(all_frames) != expected_size:
        print(f"Error: Total size {len(all_frames)} != expected {expected_size}")
        sys.exit(1)

    print(f"Total: {len(all_frames)} bytes ({FRAME_COUNT} frames x {FRAME_SIZE} bytes)")

    # Write binary file (for verification)
    bin_path = output_dir / "frames.bin"
    with open(bin_path, 'wb') as f:
        f.write(all_frames)
    print(f"Wrote {bin_path}")

    # Generate C header
    header_path = output_dir / "frames_data.h"
    generate_c_header(all_frames, header_path)
    print(f"Wrote {header_path}")

    # Verify first frame
    print("\nVerifying first frame:")
    magic, seq, ts = struct.unpack('<IIQ', all_frames[0:16])
    stored_crc = struct.unpack('<I', all_frames[5116:5120])[0]
    computed_crc = compute_crc32(all_frames[0:5116])

    print(f"  Magic:    0x{magic:08X} (expected 0x{FRAME_MAGIC:08X})")
    print(f"  Sequence: {seq}")
    print(f"  CRC32:    0x{stored_crc:08X} (computed: 0x{computed_crc:08X})")

    if magic != FRAME_MAGIC:
        print("  ERROR: Magic mismatch!")
        sys.exit(1)
    if stored_crc != computed_crc:
        print("  ERROR: CRC mismatch!")
        sys.exit(1)

    print("\nSuccess!")

if __name__ == '__main__':
    main()
